#!/usr/bin/env python3
"""
compliance_snapshot.py — Compliance Vault Script

Owner: The Arbiter (Layer 2)
Version: 2.1
Location: .workbench/scripts/compliance_snapshot.py

Generates a compliance vault for a release tag containing:
1. Traceability Matrix from state.json.feature_registry
2. All .feature files
3. state.json snapshot
4. Timestamped COMPLIANCE_SNAPSHOT summary

Usage:
  python compliance_snapshot.py --tag v1.0.0
"""

import argparse
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

STATE_JSON_PATH = Path(__file__).parent.parent.parent / "state.json"
FEATURES_DIR = Path(__file__).parent.parent.parent / "features"
VAULT_DIR = Path(__file__).parent.parent.parent / "compliance-vault"


def load_state():
    """Load state.json."""
    if not STATE_JSON_PATH.exists():
        return None
    with open(STATE_JSON_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def generate_traceability_matrix(state):
    """Generate traceability matrix from feature_registry."""
    registry = state.get("feature_registry", {})
    ownership = state.get("file_ownership", {})
    
    lines = [
        "# Traceability Matrix",
        "",
        "| REQ-ID | State | Branch | Depends On | Source Files |",
        "|--------|-------|--------|------------|--------------|",
    ]
    
    for req_id, entry in sorted(registry.items()):
        branch = entry.get("branch", "N/A")
        req_state = entry.get("state", "UNKNOWN")
        depends_on = ", ".join(entry.get("depends_on", []) or ["None"])
        
        # Find source files owned by this REQ
        owned_files = [f for f, owner in ownership.items() if owner == req_id]
        source_files = ", ".join(owned_files) if owned_files else "None"
        
        lines.append(f"| {req_id} | {req_state} | {branch} | {depends_on} | {source_files} |")
    
    return "\n".join(lines)


def create_compliance_snapshot(tag, vault_path, state):
    """Create the compliance snapshot markdown summary."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    registry = state.get("feature_registry", {})
    
    merged_features = [req for req, entry in registry.items() if entry.get("state") == "MERGED"]
    pending_features = [req for req, entry in registry.items() if entry.get("state") != "MERGED"]
    
    lines = [
        f"# COMPLIANCE SNAPSHOT — {tag}",
        "",
        f"**Generated:** {timestamp}",
        f"**Tag:** {tag}",
        f"**Version:** {state.get('version', 'unknown')}",
        "",
        "## Pipeline State",
        "",
        f"- **Current State:** {state.get('state', 'UNKNOWN')}",
        f"- **Active REQ:** {state.get('active_req_id', 'None')}",
        f"- **Stage:** {state.get('stage', 'N/A')}",
        "",
        "## Feature Summary",
        "",
        f"- **Total Features:** {len(registry)}",
        f"- **MERGED:** {len(merged_features)}",
        f"- **Pending:** {len(pending_features)}",
        "",
    ]
    
    if merged_features:
        lines.append("### MERGED Features")
        lines.append("")
        for req in sorted(merged_features):
            entry = registry[req]
            merged_at = entry.get("merged_at", "unknown")
            lines.append(f"- {req} (merged: {merged_at})")
        lines.append("")
    
    if pending_features:
        lines.append("### Pending Features")
        lines.append("")
        for req in sorted(pending_features):
            entry = registry[req]
            req_state = entry.get("state", "UNKNOWN")
            lines.append(f"- {req} (state: {req_state})")
        lines.append("")
    
    lines.extend([
        "## Files in This Vault",
        "",
        "- `state.json` — Snapshot of state.json at time of tag",
        "- `traceability-matrix.md` — REQ-ID to source file mapping",
        "- `features/` — All approved .feature files",
        "",
        "---",
        "*Generated by Agentic Workbench v2 Arbiter*",
    ])
    
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Compliance Vault Script")
    parser.add_argument("--tag", required=True, help="Release tag (e.g., v1.0.0)")
    args = parser.parse_args()
    
    tag = args.tag.lstrip("v")  # Strip leading 'v' if present
    vault_path = VAULT_DIR / f"v{tag}"
    
    print(f"[COMPLIANCE SNAPSHOT] Creating compliance vault for tag: v{tag}")
    
    # Load state
    state = load_state()
    if not state:
        print("ERROR: state.json not found", file=sys.stderr)
        sys.exit(1)
    
    # Create vault directory
    vault_path.mkdir(parents=True, exist_ok=True)
    print(f"  Created vault: {vault_path}")
    
    # 1. Copy state.json snapshot
    shutil.copy2(STATE_JSON_PATH, vault_path / "state.json")
    print("  Copied: state.json")
    
    # 2. Generate and save traceability matrix
    matrix = generate_traceability_matrix(state)
    (vault_path / "traceability-matrix.md").write_text(matrix, encoding="utf-8")
    print("  Generated: traceability-matrix.md")
    
    # 3. Copy all .feature files
    features_dest = vault_path / "features"
    features_dest.mkdir(exist_ok=True)
    if FEATURES_DIR.exists():
        for feature_file in FEATURES_DIR.glob("*.feature"):
            shutil.copy2(feature_file, features_dest / feature_file.name)
        print(f"  Copied: {len(list(features_dest.glob('*.feature')))} feature files")
    else:
        print("  No features/ directory found")
    
    # 4. Generate compliance snapshot summary
    snapshot = create_compliance_snapshot(tag, vault_path, state)
    (vault_path / "COMPLIANCE_SNAPSHOT.md").write_text(snapshot, encoding="utf-8")
    print("  Generated: COMPLIANCE_SNAPSHOT.md")
    
    print(f"\n[COMPLIANCE SNAPSHOT] Vault created successfully: {vault_path}")
    print(f"  Next: Commit and tag the release")


if __name__ == "__main__":
    main()
